// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsdGgF2Qwrwy5nX7YKVnxZbib0UoWt0hI',
    appId: '1:884717269663:web:6d6db6b2d33be86ec868aa',
    messagingSenderId: '884717269663',
    projectId: 'koffee-cbcd7',
    authDomain: 'koffee-cbcd7.firebaseapp.com',
    storageBucket: 'koffee-cbcd7.firebasestorage.app',
    measurementId: 'G-DD4970YJ9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVEtWTSY-zdignMcB_MEZDqUM9Pc5OfcM',
    appId: '1:884717269663:android:44b7f40f09c8f3dec868aa',
    messagingSenderId: '884717269663',
    projectId: 'koffee-cbcd7',
    storageBucket: 'koffee-cbcd7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsdGgF2Qwrwy5nX7YKVnxZbib0UoWt0hI',
    appId: '1:884717269663:web:30e9a85dfb733e0fc868aa',
    messagingSenderId: '884717269663',
    projectId: 'koffee-cbcd7',
    authDomain: 'koffee-cbcd7.firebaseapp.com',
    storageBucket: 'koffee-cbcd7.firebasestorage.app',
    measurementId: 'G-5TQ3KSN9NH',
  );
}
